#!/bin/bash

MANIFEST=git://github.com/DotOS/manifest.git
BRANCH=dot11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init depth=1 -u git://github.com/ShapeShiftOS/android_manifest.git -b android_11 -g default,-device,-mips,-darwin,-notdefault && git clone https://github.com/MiDoNaSR545/mainfest_personal.git depth 1 -b ssos .repo/local_manifests && repo sync -c no-clone-bundle no-tags optimized-fetch prune force-sync -j8 || repo sync -c no-clone-bundle no-tags optimized-fetch prune force-sync -j8
